### ISSUE TITLE
Data Preprocessing scripts

### ISSUE THREAD

**Issue by zhangj1an** [shikharbahl/vrb#1]
Hi,

Great work! I feel it should be submitted to RSS instead of CVPR haha :D really high quality. A similar 2023 RSS paper is [here](https://human-world-model.github.io/#).

I am writing to ask if data preprocessing scripts for contact points and motion trajectories will be released. Or a pointer to relevant code base would be helpful. 

Thanks!

**Comment by zhangj1an** [comment]
Oh I found it in the [HOI codebase](https://github.com/stevenlsw/hoi-forecast/tree/master/preprocess). Thanks!

**Comment by ylee826** [comment]
Hi!Could you please send me the pre-trained weights? The download link provided by the author is no longer working.
