### ISSUE TITLE
The training code

### ISSUE THREAD

**Issue by tujun233** [shikharbahl/vrb#2]
Hello, I am very interested in your work. I would like to know if you will release the training code and dataset (raw video).

**Comment by shikharbahl** [comment]
Hi, thanks for your interest in our work! 

We are working on releasing the training data as well as the data processing pipeline. Our dataset and pipeline are inspired from https://github.com/stevenlsw/hoi-forecast. We have also additionally on Ego4D clips (LTA, STA, and moments).
