### ISSUE TITLE
Inconsistent performance

### ISSUE THREAD

**Issue by rainbow979** [shikharbahl/vrb#3]
I have tested the performance in other images. The results seem wrong.
![image](https://github.com/shikharbahl/vrb/assets/16297710/6a9a86a2-aef5-4c78-87d3-52937394e57c)

**Comment by rainbow979** [comment]
And I also found that the code uses language-sam to detect objects. So does it need to claim the name of the objects first?

**Comment by shikharbahl** [comment]
Thanks for your interest in the work! The model may not work well with all viewpoints/objects. It could also depend on the object label/crop. We are working on improving this.

In terms of the usage of language-sam: we use it for simplicity. Any method to provide object crop will work.

**Comment by rainbow979** [comment]
Thanks for the reply. I have tested several images. The results seem not very good. Is there any wrong or bug?

It would be strong if it could work on the whole image without cropping.

Another example:
![image](https://github.com/shikharbahl/vrb/assets/16297710/79433140-cac8-4e41-b3db-5651f8429059)

**Comment by jayyoung0802** [comment]
> I have tested the performance in other images. The results seem wrong. ![image](https://github.com/shikharbahl/vrb/assets/16297710/6a9a86a2-aef5-4c78-87d3-52937394e57c)

Hi @rainbow979 , the weight link is invalid, would you share the weight? Very thanks
