### ISSUE TITLE
How to obtain multiple hotspots?

### ISSUE THREAD

**Issue by ubless607** [shikharbahl/vrb#6]
@shikharbahl 
I tried to reproduce the image on the project page, but I could only get one.
Is there any option that I have to turn it on?

Expected:
![Snipaste_2024-03-21_22-27-46](https://github.com/shikharbahl/vrb/assets/5417257/44cea13f-a0b3-42dd-b4d5-34d03b099ade)

Output:
![kitchen_out](https://github.com/shikharbahl/vrb/assets/5417257/82e88abc-ab56-4b84-8899-b03419ba3de8)

**Comment by yolo01826** [comment]
Hi!Could you please send me the pre-trained weights? The download link provided by the author is no longer working.

**Comment by ubless607** [comment]
@yolo01826 Can you write your e-mail address?

**Comment by yolo01826** [comment]
***@***.***,thank you

---- Replied Message ----
| From | ***@***.***> |
| Date | 05/14/2024 12:20 |
| To | shikharbahl/vrb ***@***.***> |
| Cc | yolo01826 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [shikharbahl/vrb] How to obtain multiple hotspots? (Issue #6) |

@yolo01826 Can you write your e-mail address?

**Comment by yolo01826** [comment]
ok,my email: liyisonice@163.com ,thank you for your reply

**Comment by ubless607** [comment]
@yolo01826 sent!

**Comment by yolo01826** [comment]
😉thanks a lot

**Comment by jun7-shi** [comment]
@ubless607 hi, could you please send me the pretrained weights as well?  jun7.shi@gmail.com , thanks!

**Comment by ubless607** [comment]
@jun7-shi Sent!

**Comment by jun7-shi** [comment]
@ubless607 thanks so much.
Using the pretrained weights you provided, i could reproduce the results of multiple hotspots.

**Comment by ZY199301** [comment]
hi, could you please send me the pretrained weights as well? zhangyumit@126.com, thank you very much!

**Comment by ubless607** [comment]
@ZY199301 sent!

**Comment by JaneLin-0409** [comment]
@ubless607 hi, could you please send me the pretrained weights as well? janelin_312@163.com , thanks!

**Comment by wadeKeith** [comment]
@ubless607 Could you please send me the pretrained weights as well? [2470887663@qq.com](mailto:2470887663@qq.com), thank you very much!

**Comment by ubless607** [comment]
@JaneLin-0409 sent!

**Comment by ubless607** [comment]
@wadeKeith sent!

**Comment by fooyuhui** [comment]
@ubless607 I also need the pretrained weights. Could you send me it?  [fooyuhuii@gmail.com](mailto:fooyuhuii@gmail.com), thanks!

**Comment by Byo0923** [comment]
@ubless607 
I also need the pretrained weights too.
Could you please send me the pretrained weights as well? , ryuandtenho@yahoo.co.jp , thanks!

**Comment by ubless607** [comment]
@fuyh20 Sent!

**Comment by ubless607** [comment]
@Byo0923 Sent!

**Comment by Byo0923** [comment]
@ubless607 
I was able to download the checkpoints. Thank you very, very much. I will try it.

**Comment by Kimagure7** [comment]
I also need the pretrained weights too. Could you please send me the pretrained weights as well? [2477036173@qq.com](mailto:2477036173@qq.com) , thanks! @ubless607

**Comment by ubless607** [comment]
@Kimagure7 Sent!

**Comment by fooyuhui** [comment]
@ubless607 Thanks for the model weights. And I have already used it. You can set the manual seed in order to get different outputs, and the output is random.

**Comment by YujpVc** [comment]
I also need the pretrained weights, could you send me well? 1334136382@qq.com, thanks

**Comment by nys601350111** [comment]
Hi!Could you please send me the pre-trained weights? 601350111@qq.com   thanks!

**Comment by nys601350111** [comment]
@ubless607  I also need the pretrained weights, could you send me well? 601350111@qq.com](mailto:601350111@qq.com) thanks!

**Comment by ubless607** [comment]
@YujpVc sent!

**Comment by ubless607** [comment]
@nys601350111 sent!

**Comment by YujpVc** [comment]
thanks a lot!



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 9, 2024 00:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [shikharbahl/vrb] How to obtain multiple hotspots? (Issue #6)




 
@YujpVc sent!

**Comment by javierpey** [comment]
Hi @ubless607 or anyone in the above thread, could you send the weights to me? Thank you very much in advance! :) My email is: javier_pey@hotmail.com

**Comment by Kimagure7** [comment]
> Hi @ubless607 or anyone in the above thread, could you send the weights to me? Thank you very much in advance! :) My email is: [javier_pey@hotmail.com](mailto:javier_pey@hotmail.com)

sent!

**Comment by javierpey** [comment]
Did anyone face any issue pip installing the lang-segment-anything portion from the "pip install -U git+https://github.com/luca-medeiros/lang-segment-anything.git" command? 

Mine seems to be stuck at this portion for really really long. 

Collecting lightning<3.0.0,>=2.0.1
  Using cached lightning-2.0.2-py3-none-any.whl (1.8 MB)
  Using cached lightning-2.0.1.post0-py3-none-any.whl (1.8 MB)
  Using cached lightning-2.0.1-py3-none-any.whl (1.8 MB)

Not sure if i am doing anything wrong or it just takes super long to install. Thanks in advance again!

I will open a new issue but just wanted to ask here since some of you may be active.

**Comment by ubless607** [comment]
@Hotsburp I don't have any problem.
Did you try on new conda envrionment? / Did you update pip to the lastest version?

**Comment by javierpey** [comment]
Hi @ubless607, thanks for getting back! Yup i tried on new conda environment and also updating pip.

I think the issue is with the GroundingDino that LangSegmentAnything uses because there are a lot of issues with the version conflict of packages recently due to GroundingDino updates.

May i know which commit version (date or hash) of the LangSegmentAnything did you use or did you just use the latest version at that point of time? This is because this affects the version of GroundingDino used and i would also like to track back the date of the version that VRB used.

While i managed to now install somewhat properly, i had to manually find an older version of both LangSegmentAnything and GroundingDino.

But by doing so, i had this error when running demo.py using the weights:
 => _IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight'])

This results in:
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

I would appreciate if you all have any insights! :)

**Comment by ubless607** [comment]
@Hotsburp It has been a while I tested this repository. Can you check this issue?
https://github.com/luca-medeiros/lang-segment-anything/issues/66

**Comment by javierpey** [comment]
Yeap, i saw that too. No worries, i will try it out again. Thanks for you help! 

I will let you know if i find any insights to your original issue of obtaining multiple hotspots.

**Comment by ubless607** [comment]
@Hotsburp 
1. Git clone this fork version and install GroundingDINO
https://github.com/IDEA-Research/GroundingDINO/tree/df5b48a3efbaa64288d8d0ad09b748ac86f22671

2. Git clone lang-segment-anything
3. Edit pyproject.toml
- huggingface-hub = "^0.16.4, <0.17.0"
- transformers = "4.27.4"
- lightning = "2.0.1"
- erase GroundingDINO line

Can you try?

**Comment by javierpey** [comment]
@ubless607 

Yup, i will try this! May i know what is the cuda and nvidia driver versions that you were using for your case?

Update: I have managed to run the demo.py script, but i used the commit version "https://github.com/IDEA-Research/GroundingDINO/tree/da9f1c0751935e9284890572069f4b2fef4cbfdc" instead else the "supervision" versions will conflict for pillow.

I have a CUDA out of memory error so i probably need to source for a better gpu before proceeding.

**Comment by 64327069** [comment]
@ubless607  I also need the pretrained weights, could you send me well? 64327069@qq.com, thanks

**Comment by javierpey** [comment]
@ubless607 

Thanks for the info on the setup! I think it would be best to run GroundingDino using the https://github.com/IDEA-Research/GroundingDINO/tree/da9f1c0751935e9284890572069f4b2fef4cbfdc version (follow the GPU steps as well) as it is at the same time when VRB was pushed (~April 2023). LangSegAnything can be the latest version and modified based on your recommendations. Just need to make sure supervision==0.6.0, pillow==9.3.0, and CUDA==1.7 as the system will highlight dependency conflicts.

Anyway, I have managed to run the demo.py code on the images by the authors and also some generalized images. Looks like the generalization is not the best as it is limited to a few items (cup, drawer, potlid, microwave) on inference.py and performs pretty inconsistently on certain viewpoints. But i think the author has addressed that it does not always work well in the https://github.com/shikharbahl/vrb/issues/3#issue-1886937851 issue.  

Also, do you happen to have the actual input image that you were using above? I wanted to test and maybe see if i have the same results as you but i can't find it on the project page.  

The project has a lot of potential and i hope @shikharbahl releases the training code soon for future works!

**Comment by ubless607** [comment]
@64327069 Sent!

**Comment by ubless607** [comment]
@Hotsburp I am glad that you were able to reproduce the environment setting.

![vrb_initial_v2_compressed](https://github.com/user-attachments/assets/b84cb835-b660-4ee5-bd15-32fe079663e0)

**Comment by javierpey** [comment]
@ubless607 During running demo.py on this image. Do you face the error "ValueError: tile cannot extend outside image"? I think i may be something to do with image crop as the error comes from the input_img in Line 84 of inference.py. 

If i input img instead of input_img in Line 84, i get this:

![kitchen_out4](https://github.com/user-attachments/assets/f26af901-17d9-43bd-9210-ac618c5de18d)

I guess there is still multiple hotspots but the script is sensitive to the cropped image and its dimensions.

**Comment by bethalageetachandraraju** [comment]
can anyone from the above thread send me pretrained weights please, my email: gb2643@nyu.edu 
@ubless607 @Byo0923 @wadeKeith @JaneLin-0409 @64327069 @Kimagure7

**Comment by ojh6404** [comment]
> can anyone from the above thread send me pretrained weights please, my email: [gb2643@nyu.edu](mailto:gb2643@nyu.edu) @ubless607 @Byo0923 @wadeKeith @JaneLin-0409 @64327069 @Kimagure7

Could anyone send me pretrained weights, too? my email : ojh6404@gmail.com

**Comment by achrxme-1838** [comment]
could anyone from the above thread send me pretrained weights too please, my email: shlim@kaist.ac.kr
I'll be very appreciate it!!
@ubless607 @Byo0923 @wadeKeith @JaneLin-0409 @64327069 @Kimagure7

**Comment by ubless607** [comment]
@achrxme-1838 @ojh6404 @bethalageetachandraraju Sent!

**Comment by achrxme-1838** [comment]
Thank you-!!!!

2024년 8월 19일 (월) 오후 8:44, ubless607 ***@***.***>님이 작성:

**Comment by ubless607** [comment]
> @ubless607 During running demo.py on this image. Do you face the error "ValueError: tile cannot extend outside image"? I think i may be something to do with image crop as the error comes from the input_img in Line 84 of inference.py.
> 
> If i input img instead of input_img in Line 84, i get this:
> 
> ![kitchen_out4](https://private-user-images.githubusercontent.com/68238160/354039937-f26af901-17d9-43bd-9210-ac618c5de18d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjc1ODgsIm5iZiI6MTcyNDA2NzI4OCwicGF0aCI6Ii82ODIzODE2MC8zNTQwMzk5MzctZjI2YWY5MDEtMTdkOS00M2JkLTkyMTAtYWM2MThjNWRlMThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDExMzQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNGJjODRmODFkZjQwYTkxNzVkNDEwZDcyZGMwZjg3M2M3MWM4ZjkyODcyMTIxYjA0ZmZjNjliODA0YTAzZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HB67vez2MAEJmUt14HWYBrj7JLzfaRaTaVPVtpW4RYs)
> 
> I guess there is still multiple hotspots but the script is sensitive to the cropped image and its dimensions.

I didn't encounter that error message. Have you done any additional work on this?

**Comment by Tom-Huang** [comment]
could anyone from the above thread send me pretrained weights too please, my email: huang@informatik.uni-freiburg.de

**Comment by ubless607** [comment]
@Tom-Huang Sent!

**Comment by javierpey** [comment]
Hey @ubless607, yeap i tried out a few more use cases but it is sensitive to the image size and dimensions. As mentioned, I got good results only for certain tasks and angles but there are also a lot of wrong trajectories too haha.

Would be good that they release more tasks and also how this can be used for 3d pose/state beyond 2d image coordinates.

What about yourself, did you explore more too?

**Comment by codepk37** [comment]
@ubless607 @Byo0923 @wadeKeith @JaneLin-0409 @64327069 @Kimagure7 Could anyone please send me the pretrained weights aswell? (mailto: karkepavan230@gmail.com)

**Comment by ubless607** [comment]
@Hotsburp I didn't try on this much further :(

**Comment by ubless607** [comment]
@codepk37 Sent!

**Comment by ashiqfauna** [comment]
@ubless607 Could you please send me the pretrained weights as well? (mailto: [ashiq](mailto:ashiqrahman741@gmail.com)).

Thanks :)

**Comment by ubless607** [comment]
@ashiqfauna Sent!

**Comment by dtbpkmte** [comment]
@ubless607 Can I have the weights please? My email address is dtbpkmte@gmail.com. Thank you!

**Comment by ubless607** [comment]
@dtbpkmte Sent!

**Comment by ZTE-dzq** [comment]
@ubless607 I also need the pretrained weights, could you send me? My email address is 530995114@qq.com , thanks!

**Comment by prac-101** [comment]
@ubless607 @Byo0923 @wadeKeith @JaneLin-0409 @64327069 @Kimagure7 I also need the pretrained weights, could anyone please send me the pretrained weights too please? My email address is 2281915806ms@gmail.com, thanks a lot!

**Comment by tindarin** [comment]
@ubless607 @Byo0923 @Tom-Huang @wadeKeith @dtbpkmte @prac-101 @dtbpkmte I also need the pretrained weights, could anyone send me? My email address is a2458149084@163.com or hu393435347@gmail.com , thanks!

**Comment by SuQinghang** [comment]
@ubless607 Could you please send me the pre-trained weights as well? My email address is qinghang.su@gmail.com. Thanks!

**Comment by ubless607** [comment]
@ZTE-dzq @SuQinghang @tindarin @prac-101 Sent!

**Comment by shubhgoel20** [comment]
@ubless607 Hi could you please send me the pretrained weights as the link provided in the readme is not working. Email: shgoel@ethz.ch 
Thanks in advance

**Comment by mschoene** [comment]
@ZTE-dzq @SuQinghang @tindarin @prac-101 @ubless607 Could you send me the pretrained weights as well? Thanks a lot in advance!
myriam@kaist.ac.kr

**Comment by SuQinghang** [comment]
> @ZTE-dzq @SuQinghang @tindarin @prac-101 @ubless607 Could you send me the pretrained weights as well? Thanks a lot in advance! [myriam@kaist.ac.kr](mailto:myriam@kaist.ac.kr)

@mschoene Sent!

**Comment by hwh23** [comment]
@ubless607 @SuQinghang @mschoene @ZTE-dzq  Hi! Could you please send me the pretrained weights as well, my email: 
2530670013@qq.com
Thanks a lot in advance!

**Comment by earth15354** [comment]
@ubless607 @SuQinghang @mschoene @ZTE-dzq @hwh23 Hi! If you have the model weights, can you please send me the model weights as well? Thank you very much in advance!

My email is [jitpuwapat_mokkamakkul@brown.edu](url)

**Comment by taeyeopl** [comment]
@ubless607 @mschoene @achrxme-1838 Could I also have a chance to get the pre-trained weights? 

Thanks in advance.

taeyeop.trevor@gmail.com

**Comment by Arunkumar137** [comment]
@ubless607 @mschoene  @tindarin @ZTE-dzq @SuQinghang @tindarin @prac-101 Could you send me the pretrained weights as well? Thanks (transformergptdev@gmail.com)

**Comment by zlm200** [comment]
@ubless607 @mschoene @Byo0923 @SuQinghang @Tom-Huang @ Could you send me the pretrained weights as well? Thanks  （3063076290@qq,com）

**Comment by zlm200** [comment]
@ubless607 @mschoene @Byo0923 @SuQinghang @Tom-Huang Could you send me the pretrained weights as well? Thanks （3063076290@qq.com）

**Comment by yixiaoshenghua** [comment]
@ubless607 @mschoene @Byo0923 @SuQinghang @Tom-Huang Could you send me the pretrained weights as well? Thanks (1186344842@qq.com)

**Comment by didpurwanto** [comment]
Hi @ubless607 , could you also send me the the pretrained weights? thanks. my email is didpurwanto@gmail.com
