### ISSUE TITLE
pretrained weights does not exist

### ISSUE THREAD

**Issue by ylee826** [shikharbahl/vrb#7]
Hi!Could you please send me the pre-trained weights? The download link provided by the author is no longer working.

**Comment by wadeKeith** [comment]
@yolo01826 could you please send me pre-trained weights? Email: 2470887663@qq.com

**Comment by Kimagure7** [comment]
> @yolo01826 could you please send me pre-trained weights? Email: [2470887663@qq.com](mailto:2470887663@qq.com)

Have you received the pre-trained weights?

**Comment by omarrayyann** [comment]
@yolo01826 Could you please send me the pretrained weights. Email olr7742@nyu.edu

**Comment by ZainZh** [comment]
> Hi!Could you please send me the pre-trained weights? The download link provided by the author is no longer working.
Hi Could you please send me the pretrained weights. Email: zhengsun@link.cuhk.edu.hk

**Comment by zixinzhang02** [comment]
Have you received the the pre-trained weights? If so, could you please send me the pretrained weights?
Email: zzhang300@connect.hkust-gz.edu.cn

**Comment by omarrayyann** [comment]
If i remember correctly they haven’t shared it
